-- v1.6.2 Maxsus Quiz: avtomatik 72 talik progressdan butunlay alohida navbat
create table if not exists public.special_quizzes (
  id bigint generated by default as identity primary key,
  question text not null,
  options jsonb not null,
  correct_option integer not null check (correct_option between 0 and 3),
  explanation text,
  category text,
  status text not null default 'queued' check (status in ('queued','sent')),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  sent_count integer not null default 0,
  failed_count integer not null default 0
);
create index if not exists special_quizzes_status_id_idx on public.special_quizzes(status,id);
